# **Getting Started**

To use Numpy in Python, we can import the numpy package as follows:

In [2]:
import numpy as np
import pandas as pd

#**Ndarray and its Attributes**

In [3]:
#ndarray.ndim
arr = np.array([[3,4,6], [0,8,1]])
  
res = np.ndim(arr) #returns the axes or dimensions
  
print (res)


2


In [4]:
#ndarray.shape
arr = np.array([[3,4,6], [0,8,1]])
  
res = np.shape(arr) #returns the no. of rows and columns present
  
print (res)
arr

(2, 3)


array([[3, 4, 6],
       [0, 8, 1]])

In [ ]:
#ndarray.size
arr = np.array([[3,4,6], [0,8,1]])
  
res = np.size(arr)          #function returns no. of elements
  
print (res)

6


In [ ]:
#ndarray.dtype
arr = np.array([[3,4,6], [0,8,1]])

print(arr.dtype)         #tells the data type of the elements of a NumPy array 



int64


In [ ]:
#ndarray.itemsize
arr = np.array([[3,4,6], [0,8,1]])
  
res = arr.itemsize     #returns the size of each element
  
print (res)

8


**Creating a NumPy ndarray Object**

In [ ]:
arr = np.array([1, 2, 3, 4, 5]) 
print(arr) 
print(type(arr))



[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# more than one dimensions 
 
a = np.array([[1, 2,3], [9, 4,8]]) 
print(a)

[[1 2 3]
 [9 4 8]]


**Dimensions in Arrays**

In [ ]:
#0-D Arrays
 
arr = np.array(42) 
print(arr) 

42


In [ ]:
#1-D arrays

arr = np.array([1, 2, 3, 4, 5]) 
print(arr) 

[1 2 3 4 5]


In [ ]:
#2-D arrays

arr = np.array([[1, 2, 3], [4, 5, 6]]) 
print(arr) 

[[1 2 3]
 [4 5 6]]


**NumPy Array Indexing and Slicig**

In [ ]:
#example 1

arr = np.array([1, 2, 3, 4, 5, 6, 7]) 
print(arr[1:5])

[2 3 4 5]


In [ ]:
#example 2
 
arr = np.array([1, 2, 3, 4, 5, 6, 7]) 
print(arr[4:])

[5 6 7]


In [ ]:

arr = np.array([1, 2, 3, 4, 5, 6, 7]) 
print(arr[::2])

[1 3 5 7]


In [ ]:
#indexing example
a = ['spam', 'egg', 'bacon', 'tomato', 'ham', 'lobster'] 
a[5]  

'lobster'

In [ ]:
a[len(a)-1]


'lobster'

In [ ]:
a[-1] 

'lobster'

# Numpy Functions



**numPy.where()**


**using np.where() with a condition**

In [ ]:

arr = np.array([[-1, 2, -3], [4, 5, -6]])
b=np.where(arr < 0, "Negative", "Positive")

print(b)

[['Negative' 'Positive' 'Negative']
 ['Positive' 'Positive' 'Negative']]


**using numPy.where() in a dataframe**

In [ ]:
#creating a dataFrame
record  = pd.DataFrame({"Name":["Anu", "Bishwa", "Keshav",
                             "Ravi", "Ria", "Kevin"],
                   "Age": [18,23,10,16,27,8]})
print("Old Record\n",record)
#Suppose, we want to create a new column that tells whether a person is eligible to vote or not, Here we can use np.where() .
record["Eligibility"]= np.where(record["Age"]>=18, "Eligible", "Not Eligible")
print("\n After adding new colum\n",record)

Old Record
      Name  Age
0     Anu   18
1  Bishwa   23
2  Keshav   10
3    Ravi   16
4     Ria   27
5   Kevin    8

 After adding new colum
      Name  Age   Eligibility
0     Anu   18      Eligible
1  Bishwa   23      Eligible
2  Keshav   10  Not Eligible
3    Ravi   16  Not Eligible
4     Ria   27      Eligible
5   Kevin    8  Not Eligible


# Functions of Rounding

**np.around ()**


In [ ]:
arr = np.array([1.09,5.55, 123, 0.567, 25.532])
print("Input array = ", arr)

print("\nAfter Rounding:") 
print(np.around(arr))
print(np.around(arr, decimals =1))
print(np.around(arr, decimals =-1))

Input array =  [  1.09    5.55  123.      0.567  25.532]

After Rounding:
[  1.   6. 123.   1.  26.]
[  1.1   5.6 123.    0.6  25.5]
[  0.  10. 120.   0.  30.]


**np.floor()**


In [ ]:
arr = [0.23, 5.79, 1.2, 4.24, 9.99]  
print("Original array:",arr)  
new_arr = np.floor(arr) 
#After applying the floor function
print("\nAfter using the floor function \nOutput array:",new_arr) 

Original array: [0.23, 5.79, 1.2, 4.24, 9.99]

After using the floor function 
Output array: [0. 5. 1. 4. 9.]


**np.ceil()**

In [ ]:
arr = [0.23, 5.79, 1.2, 4.24, 9.99]  
print("Original array:",arr)  
new_arr = np.ceil(arr) 
#After applying the ceil function
print("\nAfter using the ceil function \nOutput array:",new_arr)

Original array: [0.23, 5.79, 1.2, 4.24, 9.99]

After using the ceil function 
Output array: [ 1.  6.  2.  5. 10.]


# Basic Statistic Function



**np.sum()**

In [ ]:
import numpy as np

In [ ]:
#1D array
np.sum([0.5, 1.5])


2.0

In [ ]:
#2D array
np.sum([[0, 1], [0, 5]])

6

**np.mean()**

In [ ]:
# 1D array
a = np.array([1,2,3,4,5,6,7])
np.mean(a)

4.0

In [ ]:
#2D array
a = np.array([[1, 2], [3, 4]])
np.mean(a)

2.5

**np.median()**

In [ ]:
# For 1D Array
arr = [2, 2, 7, 1,3,9, 34]
  
print("arr : ", arr) 
print("Median of array : ", np.median(arr))


arr :  [2, 2, 7, 1, 3, 9, 34]
Median of array :  3.0


In [ ]:
# for 2D Array
arr=arr = [[14, 17, 12, 33, 44],  
       [15, 6, 27, 8, 19], 
       [23, 2, 54, 1, 4, ]] 
print("\n Median of array, axis = 0 : ", np.median(arr, axis = 0)) 
   
# median along the axis = 1 
print("\n Median of array, axis = 1 : ", np.median(arr, axis = 1))



 Median of array, axis = 0 :  [15.  6. 27.  8. 19.]

 Median of array, axis = 1 :  [17. 15.  4.]


**np.std()**


This function computes the standard deviation

In [ ]:
arr = [2, 2, 7, 1,3,9, 34]
  
print("arr : ", arr) 
print("Standard Deviation of array : ", np.std(arr))

arr :  [2, 2, 7, 1, 3, 9, 34]
Standard Deviation of array :  10.845858797772747


In [ ]:
# for 2D Array
arr=arr = [[14, 17, 12, 33, 44],  
       [15, 6, 27, 8, 19], 
       [23, 2, 54, 1, 4, ]] 
print("\n Standard Deviation of array, axis = 0 : ", np.std(arr, axis = 0)) 
   
# median along the axis = 1 
print("\n Standard Deviation of array, axis = 1 : ", np.std(arr, axis = 1))


 Standard Deviation of array, axis = 0 :  [ 4.02768199  6.3420992  17.3781472  13.73559852 16.49915823]

 Standard Deviation of array, axis = 1 :  [12.44186481  7.61577311 20.27214838]
